apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-user-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/zipgaskkukdp/hospital-service-app.git'
    targetRevision: main
    path: manifests/overlays/dev/auth-user-service # 👈 경로 확인!
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true